export const PREDEFINED_CATEGORIES = [
  // Mercado / supermercado
  "Mercearia",
  "Massas e Grãos",
  "Molhos e Condimentos",
  "Temperos e Especiarias",
  "Enlatados e Conservas",
  "Hortifruti",
  "Frutas",
  "Legumes",
  "Verduras",
  "Açougue",
  "Peixaria",
  "Padaria",
  "Confeitaria",
  "Frios",
  "Frios e Laticínios",
  "Laticínios",
  "Congelados",
  "Bebidas",
  "Bebidas Alcoólicas",
  "Doces e Sobremesas",
  "Biscoitos e Snacks",
  "Salgadinhos & Snacks",
  "Matinais",

  // Lanchonete / restaurante
  "Lanches",
  "Pizzaria",
  "Pratos",
  "Marmitas",
  "Porções",
  "Saladas",
  "Sopas",
  "Salgados",
  "Sorveteria",
  "Açaí e Sucos",
  "Cafeteria",
  "Combos e Promoções",

  // Limpeza e higiene
  "Limpeza",
  "Higiene Pessoal",
  "Perfumaria",
  "Cosméticos",
  "Cuidados com Bebê",
  "Descartáveis",

  // Farmácia / saúde
  "Farmácia",
  "Suplementos",
  "Saúde e Bem-estar",

  // Pet
  "Pet Shop",

  // Loja / departamentos
  "Bebê e Infantil",
  "Brinquedos",
  "Papelaria",
  "Eletrônicos",
  "Eletrodomésticos",
  "Informática",
  "Telefonia e Acessórios",
  "Cama, Mesa e Banho",
  "Utilidades Domésticas",
  "Ferramentas",
  "Material de Construção",
  "Elétrica e Hidráulica",
  "Tintas e Acessórios",
  "Jardinagem",
  "Automotivo",
  "Calçados",
  "Vestuário",
  "Acessórios",
  "Joias e Bijuterias",
  "Esporte e Lazer",
  "Livraria",
  "Games",
  "Decoração",
  "Presentes",
  "Festas",

  // Operacional
  "Embalagens",
  "Tabacaria",
  "Recargas",
  "Serviços",
  "Outros",
];
