// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

const PROJECT_REF = (() => {
  try {
    return new URL(SUPABASE_URL).hostname.split('.')[0];
  } catch {
    return 'default';
  }
})();

const PROJECT_KEY = '__supabase_project_ref';
if (typeof window !== 'undefined') {
  const stored = localStorage.getItem(PROJECT_KEY);
  if (stored && stored !== PROJECT_REF) {
    Object.keys(localStorage).forEach((k) => {
      if (k.startsWith('sb-') || k.includes('supabase')) {
        localStorage.removeItem(k);
      }
    });
  }
  localStorage.setItem(PROJECT_KEY, PROJECT_REF);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: `sb-${PROJECT_REF}-auth-token`,
    persistSession: true,
    autoRefreshToken: true,
  }
});
